version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dcm_system
      POSTGRES_USER: dcm_user
      POSTGRES_PASSWORD: dcm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dcm_user -d dcm_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://dcm_user:dcm_password@db:5432/dcm_system
      - SECRET_KEY=docker-secret-key-change-in-production-2024
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=True
      - ALLOWED_HOSTS=["http://localhost:3000", "http://localhost:8000"]
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./reports:/app/reports
      - ./models:/app/models
      - ./data:/app/data
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python setup.py &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database Admin Interface (optional)
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data:
